Screen/editprofile menambahkan ui pada edit profile
Capstone-Mental-Health-Care-Group-6/mobile-capstone pull request #38
Opened 2023-11-23 15:41 UTC by JerikoJei

menambahkan ui pada edit profile
![editprofile](https://github.com/Capstone-Mental-Health-Care-Group-6/mobile-capstone/assets/142132072/f7185c1a-8e33-409b-98ba-3feb3afd8d8b)

2023-11-25 16:24 UTC, DenaRizki1 approved these changes

2023-11-25 16:24 UTC, aadeeee approved these changes
sudah oke ya @JerikoJei

2023-11-25 16:25 UTC, christyuda approved these changes

2023-11-25 16:27 UTC, abdfahmi07 reviewed
@JerikoJei nama file "edit_profile1.dart" nya bisa diganti jadi "edit_profile_screen.dart" ga?

2023-11-25 16:29 UTC, abdfahmi07 requested changes
@JerikoJei nama file "edit_profile1.dart" bisa diubah jadi "edit_profile_screen.dart" ga?

2023-11-26 12:52 UTC, JerikoJei commented
> @JerikoJei nama file "edit_profile1.dart" bisa diubah jadi "edit_profile_screen.dart" ga?

sudah ya bang

2023-11-26 12:52 UTC, JerikoJei commented
> @JerikoJei nama file "edit_profile1.dart" bisa diubah jadi "edit_profile_screen.dart" ga?

sudah ya bang

2023-11-30 15:36 UTC, itsjipa approved these changes

2023-11-30 15:37 UTC, aadeeee approved these changes
sudah oke @JerikoJei

2023-11-30 15:37 UTC, merged